FROM alpine:3.22 AS builder

ENV TONGSUO_VERSION=8.4.0

RUN sed -i "s|dl-cdn.alpinelinux.org|mirrors.aliyun.com|g" /etc/apk/repositories && \
    apk update && \
    apk add \
    git make perl gcc musl-dev linux-headers \
    ca-certificates \
    zip unzip

WORKDIR /usr/local/src
RUN git clone -b $TONGSUO_VERSION --depth=1 https://github.com/tongsuo-project/tongsuo.git tongsuo-$TONGSUO_VERSION

WORKDIR /usr/local/src/tongsuo-$TONGSUO_VERSION

RUN ./config --prefix=/usr/local/tongsuo \
    --openssldir=/usr/local/tongsuo/ssl \
    -Wl,-rpath,/usr/local/tongsuo/lib \
    enable-ec_elgamal \
    enable-ntls \
    enable-sm2 \
    enable-sm3  \
    enable-sm4 \
    -fPIC \
    -no-shared && \
    make -j$(nproc) && \
    make install && \
    make clean

ENV PATH=/usr/local/tongsuo/bin:$PATH

WORKDIR /workspace

CMD ["tongsuo","version","-a"]
